# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Register(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.name_line = QtWidgets.QLineEdit(Form)
        self.name_line.setGeometry(QtCore.QRect(150, 80, 201, 21))
        self.name_line.setObjectName("name_line")
        self.phone_line = QtWidgets.QLineEdit(Form)
        self.phone_line.setGeometry(QtCore.QRect(150, 120, 201, 21))
        self.phone_line.setObjectName("phone_line")
        self.male = QtWidgets.QRadioButton(Form)
        self.male.setGeometry(QtCore.QRect(170, 200, 41, 19))
        self.male.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/nan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.male.setIcon(icon)
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(Form)
        self.female.setGeometry(QtCore.QRect(290, 200, 51, 19))
        self.female.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/nv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.female.setIcon(icon1)
        self.female.setObjectName("female")
        self.user_type = QtWidgets.QComboBox(Form)
        self.user_type.setGeometry(QtCore.QRect(150, 160, 201, 22))
        self.user_type.setObjectName("user_type")
        self.user_type.addItem("")
        self.user_type.addItem("")
        self.user_type.addItem("")
        self.user_type.addItem("")
        self.user_type.addItem("")
        self.user_type.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 80, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.submit = QtWidgets.QPushButton(Form)
        self.submit.setGeometry(QtCore.QRect(150, 240, 201, 28))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.message_box = QtWidgets.QLineEdit(Form)
        self.message_box.setEnabled(False)
        self.message_box.setGeometry(QtCore.QRect(50, 30, 301, 21))
        self.message_box.setObjectName("message_box")

        self.retranslateUi(Form)
        self.submit.clicked.connect(Form.regi_submit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.user_type.setItemText(0, _translate("Form", "学生"))
        self.user_type.setItemText(1, _translate("Form", "老师"))
        self.user_type.setItemText(2, _translate("Form", "军人"))
        self.user_type.setItemText(3, _translate("Form", "退休职工"))
        self.user_type.setItemText(4, _translate("Form", "职工家属"))
        self.user_type.setItemText(5, _translate("Form", "校外人员"))
        self.label.setText(_translate("Form", "name:"))
        self.label_2.setText(_translate("Form", "phone:"))
        self.label_3.setText(_translate("Form", "Type:"))
        self.label_4.setText(_translate("Form", "Sex:"))
        self.submit.setText(_translate("Form", "Submit"))

