# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Search(object):
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(1081, 721)
        self.reader_id = QtWidgets.QLineEdit(Search)
        self.reader_id.setGeometry(QtCore.QRect(650, 520, 241, 21))
        self.reader_id.setObjectName("reader_id")
        self.borrow_table = QtWidgets.QTableWidget(Search)
        self.borrow_table.setGeometry(QtCore.QRect(30, 50, 331, 401))
        self.borrow_table.setObjectName("borrow_table")
        self.borrow_table.setColumnCount(0)
        self.borrow_table.setRowCount(0)
        self.line = QtWidgets.QFrame(Search)
        self.line.setGeometry(QtCore.QRect(30, 480, 1021, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Search)
        self.label.setGeometry(QtCore.QRect(540, 520, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Search)
        self.label_2.setGeometry(QtCore.QRect(540, 570, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.book_id = QtWidgets.QLineEdit(Search)
        self.book_id.setGeometry(QtCore.QRect(650, 570, 241, 21))
        self.book_id.setObjectName("book_id")
        self.return_table = QtWidgets.QTableWidget(Search)
        self.return_table.setGeometry(QtCore.QRect(380, 50, 331, 401))
        self.return_table.setObjectName("return_table")
        self.return_table.setColumnCount(0)
        self.return_table.setRowCount(0)
        self.ticket_table = QtWidgets.QTableWidget(Search)
        self.ticket_table.setGeometry(QtCore.QRect(730, 50, 321, 401))
        self.ticket_table.setObjectName("ticket_table")
        self.ticket_table.setColumnCount(0)
        self.ticket_table.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(Search)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Search)
        self.label_4.setGeometry(QtCore.QRect(380, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Search)
        self.label_5.setGeometry(QtCore.QRect(740, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.normal_search = QtWidgets.QPushButton(Search)
        self.normal_search.setGeometry(QtCore.QRect(920, 520, 131, 71))
        self.normal_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/chaxun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normal_search.setIcon(icon)
        self.normal_search.setObjectName("normal_search")
        self.label_6 = QtWidgets.QLabel(Search)
        self.label_6.setGeometry(QtCore.QRect(750, 610, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.group_book = QtWidgets.QPushButton(Search)
        self.group_book.setGeometry(QtCore.QRect(960, 650, 93, 31))
        self.group_book.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.group_book.setIcon(icon1)
        self.group_book.setObjectName("group_book")
        self.group_reader = QtWidgets.QPushButton(Search)
        self.group_reader.setGeometry(QtCore.QRect(650, 650, 93, 31))
        self.group_reader.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/readers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.group_reader.setIcon(icon2)
        self.group_reader.setObjectName("group_reader")
        self.label_7 = QtWidgets.QLabel(Search)
        self.label_7.setGeometry(QtCore.QRect(540, 650, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Search)
        self.label_8.setGeometry(QtCore.QRect(850, 650, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.MessageBox = QtWidgets.QPlainTextEdit(Search)
        self.MessageBox.setEnabled(False)
        self.MessageBox.setGeometry(QtCore.QRect(30, 500, 481, 191))
        self.MessageBox.setObjectName("MessageBox")

        self.retranslateUi(Search)
        self.normal_search.clicked.connect(Search.normal)
        self.group_reader.clicked.connect(Search.user_group)
        self.group_book.clicked.connect(Search.book_group)
        QtCore.QMetaObject.connectSlotsByName(Search)

    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "Form"))
        self.label.setText(_translate("Search", "Reader ID:"))
        self.label_2.setText(_translate("Search", "Book ID:"))
        self.label_3.setText(_translate("Search", "Borrow:"))
        self.label_4.setText(_translate("Search", "Return:"))
        self.label_5.setText(_translate("Search", "Ticket:"))
        self.label_6.setText(_translate("Search", "Group search"))
        self.label_7.setText(_translate("Search", "By Readers:"))
        self.label_8.setText(_translate("Search", "By Books:"))

